options:
  string-option:
    type: string
    default: "Default Value"
    description: "A short description of the configuration option"
  boolean-option:
    type: boolean
    default: False
    description: "A short description of the configuration option"
  int-option:
    type: int
    default: 9001
    description: "A short description of the configuration option"
  admin-password:
    type: string
    default: ""
    description: "override default password"
  snap-channel:
    type: string
    default: "edge"
    description: "default snap channel"
  base-dn:
    type: string
    default: "dc=spicule,dc=co,dc=uk"
    description: "base dn"  

