options:
  admin-password:
    type: string
    default: ""
    description: "override default password"
  channel:
    type: string
    default: "edge"
    description: "default snap channel"
  base-dn:
    type: string
    default: "dc=spicule,dc=co,dc=uk"
    description: "base dn"  

