#!/usr/bin/python3

import amulet
import requests
import unittest


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.d = amulet.Deployment()

        self.d.add('openldap')
        self.d.expose('openldap')

        self.d.setup(timeout=900)
        self.d.sentry.wait()

        self.unit = self.d.sentry['openldap'][0]

    def test_service(self):
        # test we can access over http
        page = requests.get('http://{}'.format(self.unit.info['public-address']))
        self.assertEqual(page.status_code, 200)

    def test_add_user(self):


    def test_remove_user(self):
    
        
    def test_scale_out_user(self):
    
    
    def test_backup(self):


    def test_change_port(self):


    def test_change_password(self):


    def test_ldaps:


    def test_ldap_enabled:


    def test_ldap_disabled:



    
if __name__ == '__main__':
    unittest.main()
