version: 2
jobs:
  build:
    docker:
      - image: buggtb/circleci-juju

    working_directory: /root/repo
    
    environment:
      # Customize the JVM maximum heap limit
      PUSH_TARGET: ~spiculecharms/openldap
      RELEASE_CHANNEL: edge
      TERM: linux
      TERMINFO: /etc/terminfo
    
    steps:
      - checkout
      - setup_remote_docker 
      - run: apt -y update
      - run: /run.sh
